/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_manufacturer_name_string       16
#define gattdb_system_id                      18
#define gattdb_transmit_duration              21
#define gattdb_SYS_Serial_Number              23
#define gattdb_gpin_andop_pins                27
#define gattdb_gpin_stopcmd_pins              29
#define gattdb_local_name_1                   31
#define gattdb_local_name_2                   33
#define gattdb_local_name_3                   35
#define gattdb_local_name_4                   37
#define gattdb_local_name_5                   39
#define gattdb_tx_power                       41
#define gattdb_get_tx_power                   43
#define gattdb_trig_delay                     45
#define gattdb_sniffer_mesh                   47
#define gattdb_battery_voltage                49
#define gattdb_ota_control                    52


#endif // __GATT_DB_H
